Dawnbreaker-DKP/Controllers/ClassListController.cs
using Dawnbreaker_DKP.Data.DKP;
using Dawnbreaker_DKP.Data.DKP.Enum;
using Dawnbreaker_DKP.Extensions;
using Dawnbreaker_DKP.Web.Utilities.DKP.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Dawnbreaker_DKP.Web.Controllers
{
    public class ClassListController : Controller
    {
        private IClassListUtil ClassListUtil { get; set; }

        public ClassListController(IClassListUtil classListUtil)
        {
            ClassListUtil = classListUtil;
        }

        public IActionResult Details([FromQuery] string raidRoster, [FromQuery] string classList)
        {
            var data = ClassListUtil.GetClassListData(raidRoster, classList);
            return View(data);
        }

        [Authorize("IsOfficer")]
        public IActionResult NewEntry(ClassListEntry data)
        {
            if (data == null)
            {
                TempData.AddError($"Invalid data.");
                return RedirectToAction("Details");
            }

            if (string.IsNullOrWhiteSpace(data.RaidRoster))
            {
                TempData.AddError("Raid roster must be specified.");
                return RedirectToAction("Details");
            }

            if (string.IsNullOrWhiteSpace(data.Class) || data.Class == Class.Unknown.ToString())
            {
                TempData.AddError("Class must be specified.");
                return RedirectToAction("Details");
            }

            if (string.IsNullOrWhiteSpace(data.PlayerName))
            {
                TempData.AddError("Player name must be specified.");
                return RedirectToAction("Details");
            }

            var success = ClassListUtil.AddEntry(data);
            if (!success)
            {
                TempData.AddError("Player not found.");
                return RedirectToAction("Details");
            }

            TempData.AddMessage("Entry successfully added.");
            return RedirectToAction("Details");
        }

        public IActionResult MovePlayerToBottom(string raidroster, string classtype, string playername)
        {
            var success = ClassListUtil.MovePlayerToBottom(raidroster, classtype, playername);
            if (!success)
            {
                TempData.AddError("Error occured when attempting to move player to bottom of list.");
                return RedirectToAction("Details");
            }

            return RedirectToAction("Details");
        }
    }
}

Dawnbreaker-DKP/Controllers/PermissionsController.cs
using Dawnbreaker_DKP.Extensions;
using Dawnbreaker_DKP.Models.Account;
using Dawnbreaker_DKP.Utilities;
using Dawnbreaker_DKP.Utilities.UserData.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Dawnbreaker_DKP.Controllers
{
    [Authorize("IsAdmin")]
    public class PermissionsController : Controller
    {
        public IUserPermissionLookup UserPermissionsLookup { get; }

        public PermissionsController(IUserPermissionLookup userLookup)
        {
            UserPermissionsLookup = userLookup;
        }

        public IActionResult Error()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Update()
        {
            var users = UserPermissionsLookup.GetUserPermissions();
            ViewData["Users"] = users;
            return View();
        }

        [HttpPost]
        public IActionResult Update(AccountPermission model)
        {
            if (!ModelState.IsValid)
            {
                TempData.AddError("Please correct validation errors.");
                return View();
            }

            UserPermissionsLookup.UpdatePermissionFor(model.Username, model.PermissionsLevel);
            return Update();
        }
    }
}

Dawnbreaker-DKP/Controllers/PlayerManagementController.cs
using Dawnbreaker_DKP.Extensions;
using Dawnbreaker_DKP.Web.Models.DKP;
using Dawnbreaker_DKP.Web.Utilities.DKP.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Dawnbreaker_DKP.Web.Controllers
{
    [Authorize("IsOfficer")]
    public class PlayerManagementController : Controller
    {
        private IPlayerManagementUtil PlayerManagementUtil { get; set; }

        public PlayerManagementController(IPlayerManagementUtil playerManagementUtil)
        {
            PlayerManagementUtil = playerManagementUtil;
        }

        public IActionResult Index()
        {
            ViewData["InactivePlayers"] = PlayerManagementUtil.GetInactivePlayers();
            var players = PlayerManagementUtil.GetAllPlayerNames();
            return View(players);
        }

        public IActionResult Edit([FromQuery] string playerName)
        {
            var playerDetails = PlayerManagementUtil.GetPlayerDetails(playerName);
            if (playerDetails == null)
            {
                TempData.AddError($"Player data for \"{playerName}\" not found.");
                return RedirectToAction("Index");
            }

            return View(playerDetails);
        }

        public IActionResult UpdateDetails(PlayerDetailsUpdateModel model)
        {
            var errors = false;

            var updateDetailsSuccess = PlayerManagementUtil.UpdateDetails(model);
            if (!updateDetailsSuccess)
            {
                TempData.AddError($"Error updating details for \"{model.PlayerName}\".");
                errors = true;
            }

            if (errors)
            {
                return RedirectToAction("Edit", new { playerName = model.PlayerName });
            }

            TempData.AddMessage($"Player details successfully updated.");
            return RedirectToAction("Edit", new { playerName = model.PlayerName });
        }

        public IActionResult UpdateDKP(PlayerDKPUpdateModel model)
        {
            var success = PlayerManagementUtil.UpdateDKP(model);
            if (!success)
            {
                TempData.AddError($"Error updating DKP for \"{model.PlayerName}\".");
                return RedirectToAction("Edit", new { playerName = model.PlayerName });
            }

            TempData.AddMessage($"DKP successfully updated.");
            return RedirectToAction("Edit", new { playerName = model.PlayerName });
        }

        public IActionResult Delete(PlayerDetailsUpdateModel data)
        {
            var playerName = data.PlayerName;
            if (string.IsNullOrWhiteSpace(playerName))
            {
                TempData.AddError("Could not find player.");
                return RedirectToAction("Index");
            }

            var success = PlayerManagementUtil.DeletePlayer(playerName);
            if (!success)
            {
                TempData.AddError($"Error deleting player: {playerName}.");
                return RedirectToAction("Index");
            }

            TempData.AddMessage("Player has been deleted.");
            return RedirectToAction("Index");
        }
    }
}

Dawnbreaker-DKP/Controllers/RaidSessionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Dawnbreaker_DKP.Data.DKP;
using Dawnbreaker_DKP.Extensions;
using Dawnbreaker_DKP.Web.Models.DKP;
using Dawnbreaker_DKP.Web.Utilities.DKP.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Dawnbreaker_DKP.Controllers
{
    [Authorize("IsOfficer")]
    public class RaidSessionsController : Controller
    {
        public IRaidSessionsUtil RaidSessionsUtil { get; }
        public IRaidInitParser RaidInitParser { get; }
        public IDKPEntryParser DKPEntryParser { get; }
        public IAuditUtil AuditUtil { get; }
        public IClassListUtil ClassListUtil { get; }

        public RaidSessionsController(IRaidSessionsUtil raidSessionsUtil, IRaidInitParser raidInitParser, IDKPEntryParser dkpEntryParser, IAuditUtil auditUtil, IClassListUtil classListUtil)
        {
            RaidSessionsUtil = raidSessionsUtil;
            RaidInitParser = raidInitParser;
            DKPEntryParser = dkpEntryParser;
            AuditUtil = auditUtil;
            ClassListUtil = classListUtil;
        }

        public IActionResult Error()
        {
            return View();
        }

        public IActionResult Index()
        {
            var sessions = RaidSessionsUtil.GetSessions().OrderByDescending(x => x.Date).ThenBy(x => x.RaidName).ToList();
            return View(sessions);
        }

        public IActionResult New(SessionInitModel model)
        {
            if (model == null)
            {
                TempData.AddError("Initialization string was not specified or failed to parse correctly.");
                return RedirectToAction("Index");
            }

            if (string.IsNullOrWhiteSpace(model.RaidName))
            {
                TempData.AddError("Raid name must be specified.");
                return RedirectToAction("Index");
            }

            var raidSessionData = RaidInitParser.TryParse(model, out var parseSucceeded);
            if (!parseSucceeded)
            {
                TempData.AddError("Initialization string was not specified or failed to parse correctly.");
                return RedirectToAction("Index");
            }

            var success = RaidSessionsUtil.TryAdd(raidSessionData);
            if (!success)
            {
                TempData.AddError("Error creating new raid session.");
                return RedirectToAction("Index");
            }

            TempData.AddMessage("Raid session successfully created.");
            return RedirectToAction("Manage", new { raidSessionid = raidSessionData.RaidSession.RaidSessionId });
        }

        public IActionResult Manage(Guid raidSessionId)
        {
            var session = RaidSessionsUtil.GetRaidSessionById(raidSessionId);
            ViewData["Participants"] = RaidSessionsUtil.GetRaidParticipants(raidSessionId);
            ViewData["SessionLedger"] = RaidSessionsUtil.GetSessionLedger(raidSessionId);
            ViewData["AddonData"] = GetAddonData();
            return View(session);
        }

        private string GetAddonData()
        {
            var data = AuditUtil.GetDKPTableData();
            var luaKVPs = data.Select(x => $"[\"{x.PlayerName}\"]=\"{x.DKPCurrent}\"");
            var luaTable = $"{{{string.Join(", ", luaKVPs)}}}";

            return luaTable;
        }

        public IActionResult ChangeStatus(ChangeParticipantStatusModel model)
        {
            if (string.IsNullOrWhiteSpace(model.ActivePlayers)
                && string.IsNullOrWhiteSpace(model.StandbyPlayers)
                && string.IsNullOrWhiteSpace(model.RemovePlayers))
            {
                TempData.AddError("No participant status changes specified.");
                return RedirectToAction("Manage", new {raidSessionId = model.RaidSessionId});
            }

            var activeParticipants = ParseParticipants(model.RaidSessionId, model.ActivePlayers);
            var standbyParticipants = ParseParticipants(model.RaidSessionId, model.StandbyPlayers, standby: true);
            var allParticipants = activeParticipants.Union(standbyParticipants);
            RaidSessionsUtil.ChangeParticipantStatuses(allParticipants);

            var toRemove = ParseParticipants(model.RaidSessionId, model.RemovePlayers);
            RaidSessionsUtil.RemoveParticipants(toRemove);

            TempData.AddMessage("Participant statuses successfully changed.");
            return RedirectToAction("Manage", new {raidSessionId = model.RaidSessionId});
        }

        private static List<SessionParticipant> ParseParticipants(Guid raidSessionId, string participantsStr, bool standby = false)
        {
            return (participantsStr ?? string.Empty).Split(",", StringSplitOptions.RemoveEmptyEntries)
                .Select(x => x.Trim())
                .Distinct()
                .Select(x => new SessionParticipant
                {
                    RaidSessionId = raidSessionId,
                    PlayerName = FirstCharToUpper(x),
                    Standby = standby,
                }).ToList();
        }

        private static string FirstCharToUpper(string input)
        {
            switch (input)
            {
                case null: return null;
                case "": return input;
                default: return input.First().ToString().ToUpper() + input.Substring(1);
            }
        }

        public IActionResult MakeLedgerEntry(DKPEntryModel model)
        {
            if (string.IsNullOrWhiteSpace(model.EntryString))
            {
                TempData.AddError("DKP entry data must be specified.");
                return RedirectToAction("Manage", new { raidSessionId = model.RaidSessionId });
            }

            var entry = DKPEntryParser.TryParse(model, out var parseSucceeded);
            if (!parseSucceeded)
            {
                TempData.AddError("DKP entry string was not specified or failed to parse correctly.");
                return RedirectToAction("Manage", new { raidSessionId = model.RaidSessionId });
            }

            entry.PlayerName = FirstCharToUpper(entry.PlayerName);
            RaidSessionsUtil.AddDKPEntry(entry);
            if (entry.IsSKEntry) ClassListUtil.HandleSKEntry(model.RaidSessionId, entry.PlayerName);

            TempData.AddMessage("DKP entry successfully added.");
            return RedirectToAction("Manage", new { raidSessionId = model.RaidSessionId });
        }

        public IActionResult RemoveLedgerEntry([FromQuery] Guid raidSessionId, [FromQuery] Guid entryId)
        {
            var success = RaidSessionsUtil.RemoveDKPEntry(entryId);
            if (success)
            {
                TempData.AddMessage("DKP entry removed.");
            }
            else
            {
                TempData.AddError("Error removing DKP entry.");
            }
            
            return RedirectToAction("Manage", new { raidSessionId = raidSessionId });
        }

        public IActionResult FinalizeSession(RaidSession session)
        {
            RaidSessionsUtil.CloseSession(session);
            TempData.AddMessage("Raid session closed.");
            return RedirectToAction("Index");
        }
    }
}

Dawnbreaker-DKP/Views/Shared/_Layout.cshtml
@using System.Security.Claims
@using Dawnbreaker_DKP.Data.User_Data
@using Dawnbreaker_DKP.Extensions
@{
    var Username = User.Identity?.Name ?? "Guest";
    var LoggedIn = Username != "Guest";
    var IsAdmin = User.HasClaim(ClaimTypes.Role, PermissionsLevel.Admin.ToString());
    var IsOfficer = User.HasClaim(ClaimTypes.Role, PermissionsLevel.Officer.ToString());
    var HasMessages = TempData.GetMessages().Any();
    var HasErrors = TempData.GetErrors().Any();
    var CurrentUrlPath = Context.Request.Path + "/" + Context.Request.QueryString;

    var AcceptedTAC = Context.Request.Cookies["AcknowledgedTAC"] != null;
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Dawnbreaker DKP</title>
    <link rel="shortcut icon" href="favicon.ico" />

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/lib/jquery-ui/themes/smoothness/jquery-ui.css" asp-append-version="true">
    <link rel="stylesheet" href="~/lib/tag-it/css/jquery.tagit.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/theme.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />

    <script src="~/lib/jquery/dist/jquery.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation/dist/additional-methods.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.js" asp-append-version="true"></script>
    <script src="~/lib/popper.js/dist/umd/popper.js" asp-append-version="true"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-ui/jquery-ui.min.js" asp-append-version="true"></script>
    <script src="~/lib/tag-it/js/tag-it.js" asp-append-version="true"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
</head>
<body>
    <div class="topleft">
        <span class="navbar-brand">Dawnbreaker DKP</span>
        <br />
        <div class="dropdown" align="left" style="margin: 5px 0 0 10px">
            <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                <span>Navigation</span>
            </button>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                <li>@Html.ActionLink("DKP Table", "Index", "Home")</li>
                <li>@Html.ActionLink("SK Class Lists", "Details", "ClassList")</li>
                <li>@Html.ActionLink("Loot History", "Ledger", "Home", new { itemsOnly = true })</li>
                <li>@Html.ActionLink("Full History", "Ledger", "Home")</li>
            </ul>
        </div>
        @if (IsOfficer)
        {
            <div class="dropdown" style="margin: -50px 0 0 135px">
                <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu3" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                    <span>Admin Tools</span>
                </button>
                <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                    <li>@Html.ActionLink("Session Management", "Index", "RaidSessions")</li>
                    <li>@Html.ActionLink("Player Management", "Index", "PlayerManagement")</li>
                    @if (IsAdmin)
                    {
                        <li>@Html.ActionLink("Set Permissions", "Update", "Permissions")</li>
                    }
                </ul>
            </div>
        }
    </div>
    <div class="topright">
        <span class="navbar-brand">Welcome, @Username</span>
        <br />
        <div class="dropdown" align="right" style="margin: 5px 10px 0 0">
            <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span>Account</span>
            </button>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenu2">
                @if (LoggedIn)
                {
                    <li>@Html.ActionLink("Change Password", "ChangePassword", "Account")</li>
                    <li>@Html.ActionLink("Change Email", "ChangeEmail", "Account")</li>
                    <li>@Html.ActionLink("Logout", "Logout", "Account")</li>
                }
                else
                {
                    <li>@Html.ActionLink("Login", "Login", "Account", new { lastPage = CurrentUrlPath }, htmlAttributes: null)</li>
                    <li>@Html.ActionLink("Register", "Register", "Account", new { lastPage = CurrentUrlPath }, htmlAttributes: null)</li>
                }
            </ul>
        </div>
    </div>
    <div class="container-fluid bodycontent">

        @if (!LoggedIn && !AcceptedTAC)
        {
            <div class="panel-primary collapse show" style="margin-top: 10px; margin-bottom: 20px" id="tac-panel">
                <button id="acknowledgeTAC" class="close btn btn-secondary" type="button" data-toggle="collapse" data-target="#tac-panel" aria-expanded="false">
                    <span size="12">&times;</span>
                </button>
                <div class="panel-heading">
                    <strong>NOTICE:</strong> By using this site, you agree to the <a href="/Home/TAC" target="_blank"><u>Terms and Conditions</u></a>.
                </div>
            </div>
        }

        @if (HasMessages)
        {
            <div class="panel-info collapse show" id="messages-panel">
                <button class="close btn btn-secondary" type="button" data-toggle="collapse" data-target="#messages-panel" aria-expanded="false">
                    <span size="12">&times;</span>
                </button>
                <div class="panel-heading">
                    <strong>Note:</strong>
                </div>
                <div class="panel-body">
                    <ul>
                        @foreach (var msg in TempData.GetMessages())
                        {
                            <li>@msg</li>
                        }
                    </ul>
                </div>
            </div>
        }
        <div class="panel panel-default">
            <div class="panel-heading">
                <h2>@ViewData["Title"]</h2>
            </div>
            <div class="panel-body">
                @if (HasErrors)
                {
                    <div class="container-fluid">
                        <div class="panel-danger">
                            <div class="panel-heading">
                                <strong>Errors:</strong>
                            </div>
                            <div class="panel-body">
                                <ul>
                                    @foreach (var error in TempData.GetErrors())
                                    {
                                        <li>@error</li>
                                    }
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="container-fluid">
                        @RenderBody()
                    </div>
                }
                else
                {
                    @RenderBody()
                }
            </div>
        </div>
    </div>

    @RenderSection("Scripts", required: false)
    <script type="text/javascript">
        $(document).ready(function () {
            $('#acknowledgeTAC').click(function () {
                var exdate = new Date();
                exdate.setDate(exdate.getDate() + 60);
                var c_value = "true; expires=" + exdate.toUTCString();
                document.cookie = "AcknowledgedTAC" + "=" + c_value;
            });
        });
    </script>
</body>
</html>