Dawnbreaker-DKP/Controllers/ClassListController.cs
using Dawnbreaker_DKP.Data.DKP;
using Dawnbreaker_DKP.Data.DKP.Enum;
using Dawnbreaker_DKP.Extensions;
using Dawnbreaker_DKP.Web.Utilities.DKP.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Dawnbreaker_DKP.Web.Controllers
{
    public class ClassListController : Controller
    {
        private IClassListUtil ClassListUtil { get; set; }

        public ClassListController(IClassListUtil classListUtil)
        {
            ClassListUtil = classListUtil;
        }

        public IActionResult Details([FromQuery] string raidRoster, [FromQuery] string classList)
        {
            var data = ClassListUtil.GetClassListData(raidRoster, classList);
            return View(data);
        }

        [Authorize("IsOfficer")]
        public IActionResult NewEntry(ClassListEntry data)
        {
            if (data == null)
            {
                TempData.AddError($"Invalid data.");
                return RedirectToAction("Details");
            }

            if (string.IsNullOrWhiteSpace(data.RaidRoster))
            {
                TempData.AddError("Raid roster must be specified.");
                return RedirectToAction("Details");
            }

            if (string.IsNullOrWhiteSpace(data.Class) || data.Class == Class.Unknown.ToString())
            {
                TempData.AddError("Class must be specified.");
                return RedirectToAction("Details");
            }

            if (string.IsNullOrWhiteSpace(data.PlayerName))
            {
                TempData.AddError("Player name must be specified.");
                return RedirectToAction("Details");
            }

            var success = ClassListUtil.AddEntry(data);
            if (!success)
            {
                TempData.AddError("Player not found.");
                return RedirectToAction("Details");
            }

            TempData.AddMessage("Entry successfully added.");
            return RedirectToAction("Details");
        }

        public IActionResult MovePlayerToBottom(string raidroster, string classtype, string playername)
        {
            var success = ClassListUtil.MovePlayerToBottom(raidroster, classtype, playername);
            if (!success)
            {
                TempData.AddError("Error occured when attempting to move player to bottom of list.");
                return RedirectToAction("Details");
            }

            return RedirectToAction("Details");
        }
    }
}

Dawnbreaker-DKP/Controllers/PlayerController.cs
using Dawnbreaker_DKP.Extensions;
using Dawnbreaker_DKP.Web.Utilities.DKP.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace Dawnbreaker_DKP.Web.Controllers
{
    public class PlayerController : Controller
    {
        private IPlayerManagementUtil PlayerManagementUtil { get; set; }

        public PlayerController(IPlayerManagementUtil playerManagementUtil)
        {
            PlayerManagementUtil = playerManagementUtil;
        }

        public IActionResult Details([FromQuery] string playerName)
        {
            var playerDetails = PlayerManagementUtil.GetPlayerDetails(playerName);
            if (playerDetails == null)
            {
                TempData.AddError($"Player data for \"{playerName}\" not found.");
                return RedirectToAction("Index", "Home");
            }

            return View(playerDetails);
        }
    }
}

Dawnbreaker-DKP/Views/ClassList/Details.cshtml
@using System.Security.Claims
@using Dawnbreaker_DKP.Data.DKP
@using Dawnbreaker_DKP.Data.User_Data
@model System.Collections.Generic.List<Dawnbreaker_DKP.Web.Models.DKP.ClassListData>
@{
    ViewBag.Title = "SK Class Lists";
    var IsOfficer = User.HasClaim(ClaimTypes.Role, PermissionsLevel.Officer.ToString());
}

@Html.Partial("_TableView", Model)
@if (IsOfficer)
{
    <hr />
    @Html.Partial("_NewEntry", new ClassListEntry())
}

Dawnbreaker-DKP/Views/ClassList/_NewEntry.cshtml
@using Dawnbreaker_DKP.Data.DKP.Enum
@model Dawnbreaker_DKP.Data.DKP.ClassListEntry
@{
    var raidRosters = new SelectList(new[] { "No Roster", "Raid 1", "Raid 2" });
    var possibleClasses = new SelectList(Enum.GetNames(typeof(Class)), selectedValue: @Model.Class);
}

<h2>New Entry:</h2>
<br/>
@using (Html.BeginForm("NewEntry", "ClassList"))
{
    <div class="row">
        <div class="col-md-1">
            <h4>Raid Roster:</h4>
        </div>
        <div class="col-md-3">
            @Html.DropDownListFor(x => x.RaidRoster, raidRosters, new { @class = "form-control", style = "height:45px" })
        </div>
    </div>
    <br />
    <div class="row">
        <div class="col-md-1">
            <h4>Class:</h4>
        </div>
        <div class="col-md-3">
            @Html.DropDownListFor(x => x.Class, possibleClasses, new { @class = "form-control", style = "height:45px" })
        </div>
    </div>
    <br />
    <div class="row">
        <div class="col-md-1">
            <h4>Name:</h4>
        </div>
        <div class="col-md-3">
            @Html.TextBoxFor(x => x.PlayerName, new { @class = "form-control" })
        </div>
    </div>
    <br />
    <input type="submit" class="btn btn-primary" />
}

Dawnbreaker-DKP/Views/ClassList/_TableView.cshtml
@using System.Security.Claims
@using Dawnbreaker_DKP.Data.User_Data
@model System.Collections.Generic.List<Dawnbreaker_DKP.Web.Models.DKP.ClassListData>
@{
    Func<string, string> ClassColor = classType =>
    {
        switch (classType)
        {
            case "Druid":
                return "panel-druid";
            case "Hunter":
                return "panel-hunter";
            case "Mage":
                return "panel-mage";
            case "Priest":
                return "panel-priest";
            case "Rogue":
                return "panel-rogue";
            case "Shaman":
                return "panel-shaman";
            case "Warlock":
                return "panel-warlock";
            case "Warrior":
                return "panel-warrior";
            default:
                return "panel-default";
        }
    };
    var IsOfficer = User.HasClaim(ClaimTypes.Role, PermissionsLevel.Officer.ToString());
}

@if (!Model.Any())
{
    <h2>No Data</h2>
}
else
{
    if (IsOfficer)
    {
        <btn class="btn btn-warning" id="editBtn">Enable Edit</btn>
        <hr />
    }
    

    <div class="row">
    @foreach (var classListData in Model)
    {
        <div class="panel @ClassColor(classListData.Class)" style="width: 225px; margin: 5px 3px 5px 3px;">
            <div class="panel-heading">
                <h4>@classListData.RaidRoster - @classListData.Class</h4>
            </div>
            <div class="panel-body">
                <table class="table table-striped table-hover " style="width: 200px; margin: -15px 0px 0px -5px">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Player</th>
                            @if (IsOfficer)
                            {
                                <th>&nbsp;</th>
                            }
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var player in classListData.Players)
                        {
                            <tr>
                                <td>@player.Position</td>
                                <td>@Html.ActionLink(player.PlayerName, "Details", "Player", new { playerName = player.PlayerName }, new { target = "_blank" })</td>
                                @if (IsOfficer)
                                {
                                    <td class="moveDownBtn" style="display: none;">@Html.ActionLink("_⇊_", "MovePlayerToBottom", "ClassList", new { raidRoster = player.RaidRoster, @classType = player.Class, playerName = player.PlayerName }, new { @class = "text-warning" })</td>
                                }
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    }
    </div>

    <script type="text/javascript">
        $(document).ready(function() {
            $('#editBtn').click(function() {
                $("#editBtn").hide();
                $(".moveDownBtn").show();
            });
        });
    </script>
}